sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"

addons:
  sonarcloud:
    organization: "suminb-github"

install:
  - pip install --requirement tests/requirements.txt
  - pip install "black; python_version >= '3.6'"

script:
  - |
    if [ -x "$(command -v black)" ]; then
      black --check .
    fi
  - py.test tests --cov base62 --durations=10

after_success:
  - coveralls
  - sonar-scanner
