sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  # - "pypy"  # disable pypy builds until supported by trusty containers
  # Python development lifecycle: https://devguide.python.org/devcycle/

addons:
  sonarcloud:
    organization: "suminb-github"

install:
  - pip install --requirement tests/requirements.txt

script:
  - py.test tests --cov base62 --durations=10

after_success:
  - coveralls
  - sonar-scanner
